"""autodoc.py — Manus Sandbox Auto-Documentation Generator.

This script scans Python files in specified directories, extracts module,
class, and function docstrings, and generates a comprehensive Markdown
document (LIBRARY.md) to keep the repository documentation up-to-date.
"""

import ast
import os
from pathlib import Path
from typing import Any, Dict, List


def extract_docstring(node: ast.AST) -> str:
    """Extract docstring from an AST node."""
    if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
        return str(ast.get_docstring(node) or "No docstring provided.")
    return ""


def parse_python_file(filepath: Path) -> Dict[str, Any]:
    """Parse a Python file and extract documentation information."""
    content = filepath.read_text()
    tree = ast.parse(content)

    module_info: Dict[str, Any] = {
        "name": filepath.stem,
        "path": str(filepath.relative_to(Path.cwd())),
        "docstring": extract_docstring(tree),
        "classes": [],
        "functions": [],
    }

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            class_info: Dict[str, Any] = {
                "name": node.name,
                "docstring": extract_docstring(node),
                "methods": [],
            }
            for sub_node in node.body:
                if isinstance(sub_node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    class_info["methods"].append(
                        {
                            "name": sub_node.name,
                            "docstring": extract_docstring(sub_node),
                        }
                    )
            module_info["classes"].append(class_info)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            module_info["functions"].append(
                {
                    "name": node.name,
                    "docstring": extract_docstring(node),
                }
            )
    return module_info


def generate_markdown(modules_data: List[Dict[str, Any]]) -> str:
    """Generate Markdown content from extracted modules data."""
    md_content = "# Manus Sandbox Library Documentation\n\n"
    md_content += "This document is automatically generated by `scripts/autodoc.py`. "
    md_content += "Do not edit manually.\n\n"

    for module in modules_data:
        module_name = module["name"]
        module_path = module["path"]
        module_doc = module["docstring"]

        md_content += f"## Module: `{module_name}.py`\n\n"
        md_content += f"**Path:** `{module_path}`\n\n"
        md_content += f"```text\n{module_doc}\n```\n\n"

        if module["functions"]:
            md_content += f"### Functions in `{module_name}.py`\n\n"
            for func in module["functions"]:
                func_name = func["name"]
                func_doc = func["docstring"]
                md_content += f"#### `{module_name}.{func_name}()`\n\n"
                md_content += f"```text\n{func_doc}\n```\n\n"

        if module["classes"]:
            md_content += f"### Classes in `{module_name}.py`\n\n"
            for cls in module["classes"]:
                cls_name = cls["name"]
                cls_doc = cls["docstring"]
                md_content += f"#### `class {module_name}.{cls_name}`\n\n"
                md_content += f"```text\n{cls_doc}\n```\n\n"
                if cls["methods"]:
                    md_content += "##### Methods\n\n"
                    for method in cls["methods"]:
                        method_name = method["name"]
                        method_doc = method["docstring"]
                        md_content += f"###### `{cls_name}.{method_name}()`\n\n"
                        md_content += f"```text\n{method_doc}\n```\n\n"
    return md_content


def main() -> None:
    """Run the auto-documentation generation process."""
    repo_root = Path(__file__).parent.parent.absolute()
    os.chdir(repo_root)
    target_dirs = [repo_root / "scripts", repo_root / "tools"]

    all_modules_data: List[Dict[str, Any]] = []

    for target_dir in target_dirs:
        for filepath in target_dir.glob("*.py"):
            if filepath.name != Path(__file__).name:  # Don't document self
                print(f"Processing {filepath}...")
                all_modules_data.append(parse_python_file(filepath))

    # Sort modules by name for consistent output
    all_modules_data.sort(key=lambda x: x["name"])

    markdown_output = generate_markdown(all_modules_data)
    # Remove any trailing multiple newlines to satisfy markdownlint
    markdown_output = markdown_output.strip() + "\n"
    output_path = repo_root / "LIBRARY.md"
    output_path.write_text(markdown_output)
    print(f"\nGenerated documentation to {output_path}")


if __name__ == "__main__":
    main()
